# Generated by Django 4.2.3 on 2023-08-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_percentage_student_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_marks',
        ),
    ]
