# Generated by Django 4.2.3 on 2023-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_percentage_student_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_marks',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
