# Generated by Django 4.2.3 on 2023-08-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_student_percentage_remove_student_total_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='chemistry',
            new_name='chemistry_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='maths',
            new_name='maths_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='physics',
            new_name='physics_marks',
        ),
    ]
